/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg5_ronalzuniga;

import java.awt.Color;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Josué Zuniga
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_country = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nompais = new javax.swing.JTextField();
        dc_fundacion = new com.toedter.calendar.JDateChooser();
        tf_himno = new javax.swing.JTextField();
        b_color = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        add_person = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_nacionalidad = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        cb_genero = new javax.swing.JComboBox<>();
        tf_vocacion = new javax.swing.JTextField();
        cb_titulo = new javax.swing.JComboBox<>();
        cb_covid = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        personas = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_hombres = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_mujeres = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        m_paises = new javax.swing.JPopupMenu();
        agregar = new javax.swing.JMenuItem();
        modificar = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JMenuItem();
        m_personas = new javax.swing.JPopupMenu();
        mod = new javax.swing.JMenuItem();
        del = new javax.swing.JMenuItem();
        ex = new javax.swing.JMenuItem();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_paises = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        arbol1 = new javax.swing.JTree();
        jScrollPane5 = new javax.swing.JScrollPane();
        arbol2 = new javax.swing.JTree();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_add = new javax.swing.JMenu();
        add_pais = new javax.swing.JMenuItem();
        add_persona = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Agregar País");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Fecha de Fundación");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Himno Nacional");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Color de Bandera");

        tf_nompais.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        tf_himno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        b_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_colorMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("AGREGAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout add_countryLayout = new javax.swing.GroupLayout(add_country.getContentPane());
        add_country.getContentPane().setLayout(add_countryLayout);
        add_countryLayout.setHorizontalGroup(
            add_countryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_countryLayout.createSequentialGroup()
                .addGroup(add_countryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_countryLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(add_countryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(83, 83, 83)
                        .addGroup(add_countryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nompais)
                            .addComponent(dc_fundacion, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(tf_himno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b_color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(add_countryLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1))
                    .addGroup(add_countryLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        add_countryLayout.setVerticalGroup(
            add_countryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_countryLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(add_countryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(add_countryLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67)
                        .addGroup(add_countryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_nompais, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(add_countryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dc_fundacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4))
                    .addComponent(tf_himno, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(add_countryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_countryLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_countryLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(b_color, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("Agregar Personas");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Nacionalidad");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Nombre");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Apellido");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Edad");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Género");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Vocación");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Título Universitario");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("¿Tiene COVID-19?");

        tf_nacionalidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        tf_nombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        tf_apellido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        sp_edad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sp_edad.setValue(20);

        cb_genero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));

        tf_vocacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_vocacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_vocacionActionPerformed(evt);
            }
        });

        cb_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cb_titulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        cb_covid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cb_covid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("AGREGAR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout add_personLayout = new javax.swing.GroupLayout(add_person.getContentPane());
        add_person.getContentPane().setLayout(add_personLayout);
        add_personLayout.setHorizontalGroup(
            add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_personLayout.createSequentialGroup()
                .addGroup(add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_personLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(add_personLayout.createSequentialGroup()
                        .addGroup(add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(add_personLayout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addGroup(add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_personLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addGap(108, 108, 108)))
                        .addGroup(add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nacionalidad)
                            .addComponent(tf_nombre)
                            .addComponent(tf_apellido)
                            .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_genero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_vocacion, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(cb_titulo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_covid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(add_personLayout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        add_personLayout.setVerticalGroup(
            add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_personLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_personLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(add_personLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_vocacion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(31, 31, 31)
                .addGroup(add_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cb_covid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jl_hombres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_hombres.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_hombres);

        jl_mujeres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_mujeres.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_mujeres);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Mujeres");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Hombres");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setText("Personas Registradas");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("AGREGAR");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout personasLayout = new javax.swing.GroupLayout(personas.getContentPane());
        personas.getContentPane().setLayout(personasLayout);
        personasLayout.setHorizontalGroup(
            personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personasLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addGroup(personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personasLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personasLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(317, 317, 317))))
            .addGroup(personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(personasLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addGroup(personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(personasLayout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(121, 121, 121)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(personasLayout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17)
                            .addGap(63, 63, 63)))
                    .addGap(123, 123, 123)))
        );
        personasLayout.setVerticalGroup(
            personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personasLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(79, 79, 79))
            .addGroup(personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(personasLayout.createSequentialGroup()
                    .addGap(176, 176, 176)
                    .addGroup(personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(176, Short.MAX_VALUE)))
        );

        agregar.setText("Agregar Persona");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        m_paises.add(agregar);

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        m_paises.add(modificar);

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        m_paises.add(eliminar);

        mod.setText("Modificar Persona");
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });
        m_personas.add(mod);

        del.setText("Eliminar Persona");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        m_personas.add(del);

        ex.setText("Expulsar Persona");
        ex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exActionPerformed(evt);
            }
        });
        m_personas.add(ex);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROL DE COVID DE LA ONU");

        jl_paises.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_paises);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Países");
        arbol1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbol1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbol1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(arbol1);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Países");
        arbol2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(arbol2);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Países");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Personas por País");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Infectados por País");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel21.setText("CONTROL DE CASOS COVID-19");

        jButton4.setText("jButton4");

        Menu_add.setText("Agregar");
        Menu_add.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Menu_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_addActionPerformed(evt);
            }
        });

        add_pais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg5_ronalzuniga/add.png"))); // NOI18N
        add_pais.setText("Agregar País");
        add_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_paisActionPerformed(evt);
            }
        });
        Menu_add.add(add_pais);

        add_persona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg5_ronalzuniga/add.png"))); // NOI18N
        add_persona.setText("Agregar Personas");
        add_persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_personaActionPerformed(evt);
            }
        });
        Menu_add.add(add_persona);

        jMenuBar1.add(Menu_add);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(84, 84, 84)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel21)
                .addGap(71, 71, 71)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(168, 168, 168))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_personaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_personaActionPerformed
        add_person.setModal(true);
        add_person.pack();
        add_person.setLocationRelativeTo(this);
        add_person.setVisible(true);
    }//GEN-LAST:event_add_personaActionPerformed

    private void Menu_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_addActionPerformed

    }//GEN-LAST:event_Menu_addActionPerformed

    private void add_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_paisActionPerformed
        add_country.setModal(true);
        add_country.pack();
        add_country.setLocationRelativeTo(this);
        add_country.setVisible(true);
    }//GEN-LAST:event_add_paisActionPerformed

    private void b_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_colorMouseClicked
        color = JColorChooser.showDialog(this, "Elija un Color", color);
        b_color.setBackground(color);
    }//GEN-LAST:event_b_colorMouseClicked

    private void tf_vocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_vocacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_vocacionActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultListModel modelo = (DefaultListModel) jl_paises.getModel();
        centinela = -1;
        for (int i = 0; i < modelo.getSize(); i++) {
            if (((Pais) modelo.getElementAt(i)).getNombre().equals(tf_nompais.getText())) {
                centinela = 1;
            }
        }
        if (centinela == -1) {
            modelo.addElement(new Pais(tf_nompais.getText(),
                    dc_fundacion.getDate(), tf_himno.getText(), color));
            jl_paises.setModel(modelo);
            tf_nompais.setText("");
            tf_himno.setText("");
            dc_fundacion.setDate(new Date());
            JOptionPane.showMessageDialog(this, "Agregado Correctamente");
        }
        if (centinela == 1) {
            JOptionPane.showMessageDialog(this, "Pais ya existe");
            jl_paises.setModel(modelo);
            tf_nompais.setText("");
            tf_himno.setText("");
            dc_fundacion.setDate(new Date());
        }
        DefaultTreeModel m = (DefaultTreeModel) arbol1.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode pais = new DefaultMutableTreeNode((new Pais(tf_nompais.getText(),
                dc_fundacion.getDate(), tf_himno.getText(), color)).toString());
        DefaultMutableTreeNode mj = new DefaultMutableTreeNode("Mujeres");
        DefaultMutableTreeNode hm = new DefaultMutableTreeNode("Hombres");
        pais.add(mj);
        pais.add(hm);
        raiz.add(pais);
        m.reload();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        DefaultListModel mm = (DefaultListModel) jl_mujeres.getModel();
        DefaultListModel mh = (DefaultListModel) jl_hombres.getModel();
        if (((String) cb_genero.getSelectedItem()).equals("Femenino")) {
            mm.addElement(new Persona(tf_nacionalidad.getText(),
                    tf_nombre.getText(), tf_apellido.getText(),
                    (Integer) sp_edad.getValue(), "Femenino", tf_vocacion.getText(),
                    (String) cb_titulo.getSelectedItem(),
                    (String) cb_covid.getSelectedItem()));
            jl_mujeres.setModel(mm);
        } else {
            mh.addElement(new Persona(tf_nacionalidad.getText(),
                    tf_nombre.getText(), tf_apellido.getText(),
                    (Integer) sp_edad.getValue(), "Masculino", tf_vocacion.getText(),
                    (String) cb_titulo.getSelectedItem(),
                    (String) cb_covid.getSelectedItem()));
            jl_hombres.setModel(mh);
        }
        tf_nacionalidad.setText("");
        tf_nombre.setText("");
        tf_apellido.setText("");
        sp_edad.setValue(20);
        tf_vocacion.setText("");
        cb_titulo.setSelectedIndex(0);
        cb_covid.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "Agregado Correctamente");
    }//GEN-LAST:event_jButton2MouseClicked

    private void arbol1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbol1MouseClicked
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = arbol1.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            arbol1.setSelectionRow(row);
            Object v1
                    = arbol1.getSelectionPath().
                            getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Pais) {
                pais_seleccionado
                        = (Pais) nodo_seleccionado.
                                getUserObject();
                m_paises.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
            if (nodo_seleccionado.getUserObject() instanceof Persona) {
                persona_seleccionada
                        = (Persona) nodo_seleccionado.
                                getUserObject();
                m_personas.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_arbol1MouseClicked

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        personas.setModal(true);
        personas.pack();
        personas.setLocationRelativeTo(this);
        personas.setVisible(true);
    }//GEN-LAST:event_agregarActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        DefaultTreeModel m = (DefaultTreeModel) arbol1.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode pais = new DefaultMutableTreeNode((new Pais(tf_nompais.getText(),
                dc_fundacion.getDate(), tf_himno.getText(), color)).toString());;
        DefaultMutableTreeNode mj = new DefaultMutableTreeNode("Mujeres");
        DefaultMutableTreeNode hm = new DefaultMutableTreeNode("Hombres");
        DefaultListModel mm = (DefaultListModel) jl_mujeres.getModel();
        DefaultListModel mh = (DefaultListModel) jl_hombres.getModel();
        String nacionalidad, nombre, apellido, genero, vocacion, titulo, covid;
        int edad;

        if (jl_mujeres.getSelectedIndex() >= 0) {

            nacionalidad = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getNacionalidad();
            nombre = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getNombre();
            apellido = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getApellido();
            genero = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getGenero();
            vocacion = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getVocacion();
            titulo = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getTitulo();
            covid = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getCovid();
            edad = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getEdad();

            DefaultMutableTreeNode muj = new DefaultMutableTreeNode(new Persona(nacionalidad, nombre, apellido, edad, genero, vocacion, titulo, covid));
            mj.add(muj);
            pais.add(mj);
            raiz.add(pais);
            m.reload();
            JOptionPane.showMessageDialog(this, "Agregado Correctamente");
            mm.remove(jl_mujeres.getSelectedIndex());
            jl_mujeres.setModel(mm);
        }

        if (jl_hombres.getSelectedIndex() >= 0) {

            nacionalidad = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getNacionalidad();
            nombre = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getNombre();
            apellido = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getApellido();
            genero = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getGenero();
            vocacion = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getVocacion();
            titulo = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getTitulo();
            covid = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getCovid();
            edad = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getEdad();

            DefaultMutableTreeNode hom = new DefaultMutableTreeNode(new Persona(nacionalidad, nombre, apellido, edad, genero, vocacion, titulo, covid));
            hm.add(hom);
            pais.add(hm);
            raiz.add(pais);
            m.reload();
            JOptionPane.showMessageDialog(this, "Agregado Correctamente");
            mh.remove(jl_hombres.getSelectedIndex());
            jl_hombres.setModel(mh);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        DefaultTreeModel m
                = (DefaultTreeModel) arbol1.getModel();
        pais_seleccionado.setNombre(
                JOptionPane.showInputDialog("Nombre del pais: "));
        m.reload();
        JOptionPane.showMessageDialog(this, "Modificado correctamente");
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        int response = JOptionPane.showConfirmDialog(
                this,
                "Seguro de Eliminar?",
                "Confirm",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m
                    = (DefaultTreeModel) arbol1.getModel();
            m.removeNodeFromParent(
                    nodo_seleccionado);
            m.reload();
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        DefaultTreeModel m
                = (DefaultTreeModel) arbol1.getModel();
        persona_seleccionada.setNombre(
                JOptionPane.showInputDialog("Nombre"));
        persona_seleccionada.setApellido(
                JOptionPane.showInputDialog("Apellido"));
        m.reload();
    }//GEN-LAST:event_modActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        int response = JOptionPane.showConfirmDialog(
                this,
                "Seguro de Eliminar?",
                "Confirm",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m
                    = (DefaultTreeModel) arbol1.getModel();
            m.removeNodeFromParent(
                    nodo_seleccionado);
            m.reload();
        }
    }//GEN-LAST:event_delActionPerformed

    private void exActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exActionPerformed
        DefaultListModel mm = (DefaultListModel) jl_mujeres.getModel();
        DefaultListModel mh = (DefaultListModel) jl_hombres.getModel();
        String nacionalidad, nombre, apellido, genero, vocacion, titulo, covid;
        int edad;

        if ((persona_seleccionada.getGenero().equals("Femenino"))) {
            int response = JOptionPane.showConfirmDialog(
                    this,
                    "Seguro de Expulsar?",
                    "Confirm",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (response == JOptionPane.OK_OPTION) {
                DefaultTreeModel m
                        = (DefaultTreeModel) arbol1.getModel();
                m.removeNodeFromParent(
                        nodo_seleccionado);
                m.reload();
            }

            nacionalidad = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getNacionalidad();
            nombre = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getNombre();
            apellido = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getApellido();
            genero = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getGenero();
            vocacion = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getVocacion();
            titulo = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getTitulo();
            covid = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getCovid();
            edad = ((Persona) mm.get(jl_mujeres.getSelectedIndex())).getEdad();
            mm.addElement(new Persona(nacionalidad, nombre, apellido, edad, genero, vocacion, titulo, covid));
            jl_mujeres.setModel(mm);
        }

        if (persona_seleccionada.getGenero().equals("Masculino")) {
            int response = JOptionPane.showConfirmDialog(
                    this,
                    "Seguro de Expulsar?",
                    "Confirm",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (response == JOptionPane.OK_OPTION) {
                DefaultTreeModel m
                        = (DefaultTreeModel) arbol1.getModel();
                m.removeNodeFromParent(
                        nodo_seleccionado);
                m.reload();
            }
            nacionalidad = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getNacionalidad();
            nombre = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getNombre();
            apellido = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getApellido();
            genero = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getGenero();
            vocacion = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getVocacion();
            titulo = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getTitulo();
            covid = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getCovid();
            edad = ((Persona) mh.get(jl_hombres.getSelectedIndex())).getEdad();
            mh.addElement(new Persona(nacionalidad, nombre, apellido, edad, genero, vocacion, titulo, covid));
            jl_hombres.setModel(mh);
        }

    }//GEN-LAST:event_exActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_add;
    private javax.swing.JDialog add_country;
    private javax.swing.JMenuItem add_pais;
    private javax.swing.JDialog add_person;
    private javax.swing.JMenuItem add_persona;
    private javax.swing.JMenuItem agregar;
    private javax.swing.JTree arbol1;
    private javax.swing.JTree arbol2;
    private javax.swing.JButton b_color;
    private javax.swing.JComboBox<String> cb_covid;
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JComboBox<String> cb_titulo;
    private com.toedter.calendar.JDateChooser dc_fundacion;
    private javax.swing.JMenuItem del;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JMenuItem ex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> jl_hombres;
    private javax.swing.JList<String> jl_mujeres;
    private javax.swing.JList<String> jl_paises;
    private javax.swing.JPopupMenu m_paises;
    private javax.swing.JPopupMenu m_personas;
    private javax.swing.JMenuItem mod;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JDialog personas;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_himno;
    private javax.swing.JTextField tf_nacionalidad;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nompais;
    private javax.swing.JTextField tf_vocacion;
    // End of variables declaration//GEN-END:variables
private Color color;
    private int centinela;
    private DefaultMutableTreeNode nodo_seleccionado;
    private Persona persona_seleccionada;
    private Pais pais_seleccionado;
}
